### PR TITLE
Revert "Switch to nano specs on ChibiOS builds"

### LINKED ISSUE #8809: [Bug] arm-none-eabi-gcc error on Arch Linux
## Describe the Bug

I've been trying to compile and flash both a dz60rgb ansi v1 and a dz65rgb v1 in Arch Linux using the [qmk AUR package](https://aur.archlinux.org/packages/qmk/)  without success due to this error when trying to do so:
```bash
arch% qmk compile
Ψ Compiling keymap with make dztech/dz65rgb/v1:adi

QMK Firmware 0.8.120
Making dztech/dz65rgb/v1 with keymap adi

make[1]: Entering directory '/home/{my_user}/qmk_firmware'
arm-none-eabi-gcc (Arch Repository) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Linking: .build/dztech_dz65rgb_v1_adi.elf                                                           [ERRORS]
 | 
 | /usr/lib/gcc/arm-none-eabi/9.3.0/../../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/9.3.0/../../../../arm-none-eabi/lib/thumb/v7e-m/nofp/libg_nano.a(lib_a-abort.o): in function `abort':
 | abort.c:(.text.abort+0xa): undefined reference to `_exit'
 | /usr/lib/gcc/arm-none-eabi/9.3.0/../../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/9.3.0/../../../../arm-none-eabi/lib/thumb/v7e-m/nofp/libg_nano.a(lib_a-
signalr.o): in function `_kill_r':
 | signalr.c:(.text._kill_r+0xe): undefined reference to `_kill'
 | /usr/lib/gcc/arm-none-eabi/9.3.0/../../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/9.3.0/../../../../arm-none-eabi/lib/thumb/v7e-m/nofp/libg_nano.a(lib_a-signalr.o): in function `_getpid_r':
 | signalr.c:(.text._getpid_r+0x0): undefined reference to `_getpid'
 | collect2: error: ld returned 1 exit status
 | 
make[1]: *** [tmk_core/rules.mk:306: .build/dztech_dz65rgb_v1_adi.elf] Error 1
make[1]: Leaving directory '/home/{my_user}/qmk_firmware'
Make finished with errors
make: *** [Makefile:579: dztech/dz65rgb/v1:adi] Error 1
```
I tried downgrading `arm-none-eabi-gcc` back to `8.3` as [recommended on this issue](https://github.com/qmk/qmk_firmware/issues/7964#issuecomment-577210889) to no effect. I also tried removing all the arm tools dependencies and then running `./util/qmk_install.sh` but it did not help either.

## System Information

 - Keyboard:  dz65rgb v1, dz60rgb v1
   - Revision (if applicable):  
 - Operating system: Arch Linux 5.6.3
 - AVR GCC version: 8.3.0

 - ARM GCC version: 8.3.0 and 9.3.0

 - QMK Firmware version: 0.8.120

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

### PR DESCRIPTION
**Pull request by zvecr**
Reverts qmk/qmk_firmware#8270

Fixes #8809

`syscalls_cpp.cpp` contains some of the required stub functions, however on this arch environment it produces:
* ```multiple definition of `__dso_handle'```
* +2k firmware size over nosys

For the most part, ARM users are not strapped for space. So I put the case that it is better to have working builds across the board in the short term, while a potential longer term solution is worked on.

### CODE REVIEW

**Comment by tzarc** [comment]
Also confirmed that this fixes builds on Ubuntu 20.04.
