### PR TITLE
Add keymap wrappers for introspection into the keymap.

### PR DESCRIPTION
**Pull request by tzarc**
## Description

Adds some APIs for getting the number of layers defined in keymap and encoder map.
Should be useful for XAP to return extent information without requiring a `#define`.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Comment by masiullah** [comment]
I am getting the below error when compiling a userspace keymap, the keymap used to work fine earlier but now it is  not working 

Compiling: quantum/keymap_introspection.c quantum/keymap_introspection.c: In function 'keymap_layer_count':
quantum/keymap_introspection.c:9:45: error: 'keymaps' undeclared (first use in this function)
9 | #define NUM_KEYMAP_LAYERS ((uint8_t)(sizeof(keymaps) / ((MATRIX_ROWS) * (MATRIX_COLS) * sizeof(uint16_t))))

When I remove the code at line 406 in build_keyboard.mk then it works. Is there something I am missing that I need to do to make this work without build_keyboard changes

line 406 in build_keyboard.mk
$(QUANTUM_DIR)/keymap_introspection.c \

I am able to reproduce this using the below command and it is also happening to a simple user space keymap I created for myself
make splitkb/kyria/rev1:manna-harbour_miryoku

**Comment by tzarc** [comment]
Seems that keymap does some weird stuff with how it locates the keymap array.
Will have a look and raise a bugfix later today.

**Comment by drzony** [comment]
This approach breaks compile_commads.json since keymap.c is included instead of being compiled separately
