### PR TITLE
Backport fixes for GCC 8.1

### LINKED ISSUE #3316: planck/light:default doesn't compile with avr-gcc (GCC) 8.1.0 (LUFA errors)
The default keymap with current settings don't compile.

`make planck/light:default`

Gives errors relating to MIDI, turning MIDI off in
keyboards/planck/light/rules.mk
from
`MIDI_ENABLE = yes`
to
`MIDI_ENABLE = not`
and compiling produces a hex file

### PR DESCRIPTION
**Pull request by tenderlove**
Hi,

This PR just backports https://github.com/abcminiuser/lufa/commit/d8e0d67caefa312970787645180ec5db2eff92cb and https://github.com/abcminiuser/lufa/commit/a08a02481ba9e68933ad0b89483f5328767df9f3 so that QMK compiles with avr-gcc 8.1.

Before this PR, I would get:

```
Compiling: lib/lufa/LUFA/Drivers/USB/Class/Device/AudioClassDevice.c                               In file included from lib/lufa/LUFA/Drivers/USB/Class/Device/AudioClassDevice.c:38:
lib/lufa/LUFA/Drivers/USB/Class/Device/AudioClassDevice.h:382:10: error: 'EVENT_Audio_Device_StreamStartStop' alias between functions of incompatible types 'void(USB_ClassInfo_Audio_Device_t * const)' {aka 'void(struct <anonymous> * const)'} and 'void(void)' [-Werror=attribute-alias]
     void EVENT_Audio_Device_StreamStartStop(USB_ClassInfo_Audio_Device_t* const AudioInterfaceInfo)
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/lufa/LUFA/Drivers/USB/Class/Device/AudioClassDevice.c:191:6: note: aliased declaration here
 void Audio_Device_Event_Stub(void)
      ^~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
 [ERRORS]
 | 
 | 
 | 
make[1]: *** [.build/obj_planck_light_tenderlove/lib/lufa/LUFA/Drivers/USB/Class/Device/AudioClassDevice.o] Error 1
make: *** [planck/light:tenderlove] Error 1
Make finished with errors
```

After this PR everything seems to compile.  I think this also fixes #3316 

Refs: https://github.com/abcminiuser/lufa/issues/130

### CODE REVIEW

**Comment by evantravers** [comment]
If this gets approved and merged, we should probably revert this PR: https://github.com/qmk/qmk_firmware/pull/3337

**Comment by carlf** [comment]
I merged this into my local copy and it fixed all my build problems on arch.

**Comment by skullydazed** [comment]
Thanks!
