### PR TITLE
Fix compilation error with led/rgb process limit is zero.

### PR DESCRIPTION
**Pull request by daskygit**
## Description

Fixes a compilation issue introduced in #21169

When testing it also appears to fix the split indicator issues when not using the advanced option.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

File: quantum/led_matrix/led_matrix.c [hunk 1]
```diff
@@ -342,9 +342,8 @@ void led_matrix_task(void) {
         case RENDERING:
             led_task_render(effect);
             if (effect) {
-                // Only run the basic indicators in the last render iteration (default there are 5 iterations)
-                if (led_effect_params.iter == LED_MATRIX_LED_PROCESS_MAX_ITERATIONS) {
-                    led_matrix_indicators();
+                if (led_task_state == FLUSHING) {
+                    led_matrix_indicators(); //ensure we only draw basic indicators once rendering is finished
```
Comment (drashna) [inline quantum/led_matrix/led_matrix.c:346]:
```suggestion
                    led_matrix_indicators(); // ensure we only draw basic indicators once rendering is finished
```

File: quantum/rgb_matrix/rgb_matrix.c [hunk 2]
```diff
@@ -383,8 +383,7 @@ void rgb_matrix_task(void) {
         case RENDERING:
             rgb_task_render(effect);
             if (effect) {
-                // Only run the basic indicators in the last render iteration (default there are 5 iterations)
-                if (rgb_effect_params.iter == RGB_MATRIX_LED_PROCESS_MAX_ITERATIONS) {
+                if (rgb_task_state == FLUSHING) { //ensure we only draw basic indicators once rendering is finished
```
Comment (drashna) [inline quantum/rgb_matrix/rgb_matrix.c:386]:
```suggestion
                if (rgb_task_state == FLUSHING) { // ensure we only draw basic indicators once rendering is finished
```

**Review by drashna — COMMENTED** [review]
lint is bitching about these.

**Review by drashna — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]

**Review by dexter93 — APPROVED** [review]

**Review by Xelus22 — APPROVED** [review]
