### PR TITLE
Revamp replicaJunction keymaps

### PR DESCRIPTION
**Pull request by replicaJunction**
Updates both the replicaJunction Ergodox and Atreus keymaps and moves most of the logic into a new user directory.

Changes should be isolated to my keymaps rather than the core QMK logic.

### CODE REVIEW

File: layouts/community/ergodox/replicaJunction/config.h [hunk 1]
```diff
@@ -1,64 +1,19 @@
...
-You should have received a copy of the GNU General Public License
-along with this program.  If not, see <http://www.gnu.org/licenses/>.
-*/
-
-#ifndef KEYBOARDS_ERGODOX_CONFIG_H_
-#define KEYBOARDS_ERGODOX_CONFIG_H_
+#ifndef CONFIG_USER_H
+#define CONFIG_USER_H
 
 #include QMK_KEYBOARD_CONFIG_H
```
Comment (drashna) [inline layouts/community/ergodox/replicaJunction/config.h]: Neither of these incldues are needed

File: layouts/community/ergodox/replicaJunction/config.h [hunk 2]
```diff
@@ -1,64 +1,19 @@
...
-MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-GNU General Public License for more details.
-
-You should have received a copy of the GNU General Public License
-along with this program.  If not, see <http://www.gnu.org/licenses/>.
-*/
-
-#ifndef KEYBOARDS_ERGODOX_CONFIG_H_
-#define KEYBOARDS_ERGODOX_CONFIG_H_
+#ifndef CONFIG_USER_H
```
Comment (drashna) [inline layouts/community/ergodox/replicaJunction/config.h]: Could you replace the first few lines, eg, these lines: 
```c
#ifndef CONFIG_USER_H
#define CONFIG_USER_H
```
with just `#pragma one`, and remove the endif at the end?

File: keyboards/atreus/keymaps/replicaJunction/config.h [hunk 3]
```diff
@@ -1,94 +1,17 @@
-/*
-Config file - Atreus QMK with replicaJunction layout
+#ifndef CONFIG_USER_H
```
Comment (drashna) [inline keyboards/atreus/keymaps/replicaJunction/config.h]: Could you replace the first few lines, eg, these lines: 
```c
#ifndef CONFIG_USER_H
#define CONFIG_USER_H
```
with just `#pragma one`, and remove the endif at the end?

File: users/replicaJunction/replicaJunction.c [hunk 4]
```diff
@@ -0,0 +1,155 @@
+#include "replicaJunction.h"
+#include QMK_KEYBOARD_H
```
Comment (drashna) [inline users/replicaJunction/replicaJunction.c]: This line and the next shouldn't be needed.

File: users/replicaJunction/replicaJunction.h [hunk 5]
```diff
@@ -0,0 +1,118 @@
+#ifndef USERSPACE
```
Comment (drashna) [inline users/replicaJunction/replicaJunction.h]: Could you replace the first few lines, eg, these lines: 
```c
#ifndef USERSPACE
#define USERSPACE
```
with just `#pragma one`, and remove the endif at the end?

File: users/replicaJunction/replicaJunction_config.h [hunk 6]
```diff
@@ -0,0 +1,75 @@
+#ifndef USERSPACE_CONFIG_H
```
Comment (drashna) [inline users/replicaJunction/replicaJunction_config.h]: Could you replace the first few lines, eg, these lines: 
```c
#ifndef USERSPACE_CONFIG_H
#define USERSPACE_CONFIG_H
```
with just `#pragma one`, and remove the endif at the end? 


Additionally, you should rename this to just `config.h`.  This way, it will be picked up automatically, much like the keymap's config.h and processed.  And then there is no need to actually include this file on your keymap's config.

**Comment by replicaJunction** [comment]
Thanks for the feedback, and sorry for the delay in responding to your changes.

I've made the changes you requested locally, but I'm no longer able to compile the firmware - it looks like it doesn't understand `#pragma one`:

```
QMK Firmware 0.6.92
Making ergodox_ez with keymap replicaJunction and target teensy

avr-gcc (GCC) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text    data     bss     dec     hex filename
      0   24450       0   24450    5f82 .build/ergodox_ez_replicaJunction.hex

Compiling: keyboards/ergodox_ez/matrix.c                                                           In file included from <command-line>:0:0:
./users/replicaJunction/config.h:1:0: error: ignoring #pragma one  [-Werror=unknown-pragmas]
 #pragma one
 ^
cc1: all warnings being treated as errors
 [ERRORS]
 |
 |
 |
make[1]: *** [.build/obj_ergodox_ez_replicaJunction/matrix.o] Error 1
make: *** [ergodox_ez:replicaJunction:teensy] Error 1Make finished with errors
```

I'm building on Windows 10 using WSL. Is this an issue with my setup, or did I make a typo somewhere?

**Comment by drashna** [comment]
No worries on the delay, everyone has life to deal with. 

As for the pragma once stuff, that's odd.  I tested with my WSL install, and it works fine.  However, it compiles with avr gcc 4.9.2, which may be the issue. You're built may be out of date. But I think that should still be supported? 

It may be worth re-running the installation script and see if that updates things. 

(if you check my layouts, all of my config files, and userspace uses `#pragma once`.)


But if you're still having issues, then disregard the pragma stuff, for now.

**Comment by replicaJunction** [comment]
Found the issue - just a silly typo. I typed `#pragma one` rather than `#pragma once`.

I did find that replicaJunction.c didn't compile without including replicaJunction.h, so I left that include alone for now. I think I've removed the other unnecessary includes, though.

**Comment by drashna** [comment]
Sorry, yeah, you'd need the h file. But any other includes of core files are handled already.   I think that the includes are left overs of a very old format.  

But looks good
